name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
        shell: bash
      - name: Run tests (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          python -m pytest -q
        shell: bash
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pytest -q
        shell: powershell
